# Generated by Django 3.0.5 on 2020-05-27 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funds_DB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FundName', models.CharField(max_length=125)),
                ('SchemeCode', models.IntegerField()),
            ],
        ),
    ]
