# Generated by Django 3.0.5 on 2020-07-14 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0003_auto_20200603_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='debts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Deposit_Amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('start_date', models.DateField()),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('deposit_duration', models.IntegerField()),
                ('deposit_term', models.CharField(max_length=10)),
                ('compounding_term', models.CharField(max_length=10)),
            ],
        ),
    ]
