# Generated by Django 3.0.5 on 2020-07-14 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0004_debts'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='category',
            field=models.CharField(default='equity', max_length=10),
        ),
    ]
