# Generated by Django 3.0.5 on 2020-07-15 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0006_auto_20200715_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='debts',
            name='comments',
            field=models.CharField(default=True, max_length=25, null=True),
        ),
    ]
