# Generated by Django 3.0.5 on 2020-07-16 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0007_debts_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debts',
            name='deposit_duration',
        ),
        migrations.RemoveField(
            model_name='debts',
            name='deposit_term',
        ),
        migrations.AlterField(
            model_name='debts',
            name='comments',
            field=models.CharField(default='', max_length=25, null=True),
        ),
    ]
