# Generated by Django 3.0.5 on 2020-07-17 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0008_auto_20200716_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debts',
            name='id',
        ),
        migrations.AlterField(
            model_name='debts',
            name='comments',
            field=models.CharField(default='fd', max_length=25, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
