# Generated by Django 3.0.5 on 2020-07-19 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0009_auto_20200717_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='debts',
            name='Deposit_value',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='debts',
            name='maturity_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
