# Generated by Django 3.0.5 on 2020-07-19 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0010_auto_20200719_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debts',
            name='Deposit_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
